### ISSUE TITLE
djlint breaks nunjucks function call expression

### ISSUE THREAD

**Issue by Sahabial** [rtts/djhtml#109]
version: `1.34.1`

.djlintrc:
```
{
  "extension": "njk",
  "profile": "nunjucks",
  "indent": 4,
  "no_function_formatting": false,
  "preserve_leading_space": false
}
```

command:
`djlint ./src --reformat --configuration .djlintrc`

sample input:
```
<div>
    {% if apos %}
		{{ apos.singleton(data.global, "footerHead", 'apostrophe-rich-text', {
			toolbar: [ 'Styles', 'Bold', 'Italic', 'Link', 'Unlink' ],
			styles: [
				{
					name: 'footerHead',
					element: 'div',
					attributes: { class: 'footer--title-main'}
				}
			]
		}) }}
    {% endif %}
</div>
<div>
	{{ funct({
		test: 'best',
				jest: 'test',
		fest: 'pest'}) }}
</div>
```

output:
```
<div>
    {% if apos %}
        {{ apos.singleton(data.global, "footerHead", 'apostrophe-rich-text', {
                toolbar: [ 'Styles', 'Bold', 'Italic', 'Link', 'Unlink' ],
                styles: [
                {
                name: 'footerHead',
                element: 'div',
                attributes: { class: 'footer--title-main'}
                }
                ]
                }) }}
    {% endif %}
</div>
<div>{{ funct({"test": "best", "jest": "test", "fest": "pest"}) }}</div>
```

So far this is the best result I've got.

If I uise `preserve_leading_space: true` it just keeps {{}} part untouched but I want it to be formatted.

I also tried online version and got the same result.

Don't know is it something with my config or with djlint. Please help. Looks like this is the only solution for now to format nunjucks templates.

**Comment by JaapJoris** [comment]
Hi there! I think you are confusing djLint and DjHTML. The former is a big, feature-rich formatter for all kinds of template languages. The latter is this repository. To open an issue for djLint, go [here](https://github.com/djlint/djLint/issues).

In order to solve your problem, you may want to give DjHTML a try. It will never break any template, because all it does it add or remove spaces at the beginning of lines. To get started, follow the instructions in the [README](https://github.com/rtts/djhtml#installation).
