### ISSUE TITLE
How to add "elseif" for twig

### ISSUE THREAD

**Issue by hansemschnokeloch** [rtts/djhtml#117]
Hi,

I'm using djhtml to format twig files. It works very well except for `elseif` that is used by twig instead of `elif` in jinja2

How can I modify djhtml in order to recognize `elseif` as `elif` ?

Adding `elif` in twig was discussed here https://github.com/twigphp/Twig/issues/1282

**Comment by JaapJoris** [comment]
If you search the code for the string `"elif"`, you will find [this list](https://github.com/rtts/djhtml/blob/main/djhtml/modes.py#L195) of "closing and opening tags":

```python
    CLOSING_AND_OPENING_TAGS = [
        "elif",
        "else",
        "empty",
        "plural",
    ]
```

If you want your fork to support Twig's `{% elseif %}` statement, you can add it to this list. It won't be merged into mainline DjHTML though, because it (currently) only supports Django and Jinja syntaxes, which both use `{% elif %}`.
