### ISSUE TITLE
Ignore folders

### ISSUE THREAD

**Issue by koljalubitz** [rtts/djhtml#124]
Hi

is it possible to ignore some folders? VS Code automatically creates a .vscode-server folder with html files. 

Example:
```bash
djhtml .
Error: [Errno 13] Permission denied: '.vscode-server/bin/e10f2369d0d9614a452462f2e01cdc4aa9486296/extensions/github-authentication/media/index.html'
```

**Comment by JaapJoris** [comment]
Hi there,

It is possible to specify the folders you want to reindent. The folder `.` means "the current folder". If you want to reindent all templates in the `html` folder, you would invoke DjHTML like so:

```
djhtml ./html
```

With some cleverness, you could also come up with a command like this that provides a list of directories to indent which consists of every directory except `.vscode-server`:

```
djhtml $(echo */ | grep -v .vscode-server)
```

Still, the best way to use DjHTML is to configure the `pre-commit` hook as described [in the README](https://github.com/rtts/djhtml?tab=readme-ov-file#pre-commit-configuration), because then it will always be invoked automatically, so you never have to run any commands at all :nerd_face:

**Comment by koljalubitz** [comment]
Hi thanks for the tip with grep.
