### ISSUE TITLE
Allow registering own template-tags 

### ISSUE THREAD

**Issue by sjoerdjob** [rtts/djhtml#16]
While HTML and CSS and JS have standardised semantics, Django allows for registering ones own templatetags.

It would be great if these could also be registered with DjHTML for correct indenting.

For instance, see https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#std:templatetag-language for a template-tag that's not currently supported.

**Comment by JaapJoris** [comment]
In order to implement this, we need to introduce a config file. This could also hold other information such as preferred tabwidth (even per mode!).

My vote goes to naming the config file `setup.cfg`, because this integrates nicely with many Django projects and it can be parsed with [configparser](https://docs.python.org/3/library/configparser.html) without introducing extra dependencies.
