### ISSUE TITLE
Only output modified files

### ISSUE THREAD

**Issue by richarddewit** [rtts/djhtml#25]
Currently when running the hook it shows all files it has _operated_ on (so when running `pre-commit run --all-files` it shows **all** files). Can the output only show the files that have actually changed?

**Comment by JaapJoris** [comment]
Hey there, thanks for contributing!

There are multiple options to solve this issue:

1. Don't output anything when the file hasn't changed. The disadvantage is that this can result in no output when manually running `djhtml template.html`, and the user might be confused as to why nothing seemed to happen. Compare this with Black, which would print the following: 
    ```
    All done! ✨ 🍰 ✨
    X files left unchanged.
    ```
2. Provide a new command line option such as `--be-quiet-if-no-change` and add that to the exposed pre-commit hook. This means that manual invocations will still print the `template.html is perfectly indented!` message but pre-commit invocation will not.
3. Treat the `-i` option (which is already present in the pre-commit hook) the same as a `--be-quiet-if-no-change` option. Maybe print a single `All done!` message after all the input files have been processed in order to avoid the "no output" situation.

Before I commit to this, however, I would like to know how it's possible that `black .` will print the message above, while `pre-commit run --all` will not print anything. How does Black know it's being called via a pre-commit hook?

**Comment by JaapJoris** [comment]
Further investigation revealed that Black never silences its output, but that it is pre-commit which hides Black's output when no files have changed. Black's output is always the same. I propose to mimick this output, without the need for any extra command line arguments. That would correspond to option number 3 above.

Something like this:

```
re-indented templates/template1.html
re-indented templates/template2.html
re-indented templates/template3.html
All done! ✨ 🍰 ✨
3 templates re-indented, 50 templates left unchanged.
```

But instead of cake, maybe another kind of reward?

**Comment by JaapJoris** [comment]
Hi again, I'd just like to inform you that the improved output handling has now been published in [the latest release](https://github.com/rtts/djhtml/releases/tag/v1.4.1) of DjHTML, both available here and on PyPi. Thanks again for reporting this issue :pray:
