### ISSUE TITLE
Incorrect indentation for multi-line JavaScript variable assignment

### ISSUE THREAD

**Issue by jacklinke** [rtts/djhtml#79]
This is similar to #74, but slightly different.

_Note: The code blocks below are not functional on their own - I stripped down the working code to only the lines necessary to demonstrate the error._

When doing multi-line assignment operations, I would expect a result like this, where the second line of the operation is indented and following lines are outdented once again:

```javascript
var scheduler = me._scheduler,
    wsHost = (/^wss?:\/\//i.test(me._host) ? '' : me._protocol) + me._host;
var somethingelse...
```

As a more complete example, this is what I would expect to see:

```javascript
<script>
    class WebSocketHelper {
        wsOpen() {
            var scheduler = me._scheduler,
                wsHost = (/^wss?:\/\//i.test(me._host) ? '' : me._protocol) + me._host;
            scheduler.maskBody(`<div style="text-align: center">Connecting to<br>${wsHost}</div>`);
            var socket = me._socket = new WebSocket(wsHost);
            socket.onerror = () => {
                scheduler.maskBody('Error connecting to server!');
            };
        }
    }
</script>
```

Instead, I am getting:

```javascript
<script>
    class WebSocketHelper {
        wsOpen() {
            var scheduler = me._scheduler,
            wsHost = (/^wss?:\/\//i.test(me._host) ? '' : me._protocol) + me._host;
                scheduler.maskBody(`<div style="text-align: center">Connecting to<br>${wsHost}</div>`);
                var socket = me._socket = new WebSocket(wsHost);
                socket.onerror = () => {
                    scheduler.maskBody('Error connecting to server!');
                };
            }
        }
        </script>
```

(BTW, djhtml is one of my favorite packages. It's not big or flashy, but much like black and isort, it makes the development experience *so much nicer*. Thanks for building & maintaining this!)

**Comment by JaapJoris** [comment]
Thank you for your compliment, and also thank you for reporting this bug. I've looked into it and there actually 2 separate issues here:

1. DjJS mode does currently not support multi-line variable assignment, so I would have expected your example to indent like this:

```
var scheduler = me._scheduler,
wsHost = (/^wss?:\/\//i.test(me._host) ? '' : me._protocol) + me._host;
var somethingelse...
```

2. The reason this does not happen is because DjJS thinks the second line contains a comment: everything following the `//`. This is what it thinks you meant:

```
var scheduler = me._scheduler,
wsHost = (foo // Ignore me
    var somethingelse...
)
```

I will try to find a solution to both these problems!

**Comment by JaapJoris** [comment]
I'm glad to announce that both issues are now fixed in the next release of DjHTML :partying_face: 

It was trickier than I expected, because you cannot rely on a `var` statement ending with a `;` due to [ASI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion). The following will be indented correctly, with or without semicolons:

```javascript
var a = 1,
    b = 2,
    c = 3

var a = 1
  , b = 2
  , c = 3
```

However, the following will not:

```javascript
var a = 1
    b = 2
    c = 3
```

Adding a semicolon fixes it:

```javascript
var a = 1;
b = 2
c = 3
```

See the [added unittest](https://github.com/rtts/djhtml/commit/bae7427f07e7376ae992fa7be42584947f09a893#diff-3f64452eda9c0f6492fa2c141b29589dff76e2cd88daee3496ac386f67879672) for all the supported use cases.

**Comment by JaapJoris** [comment]
The previous failing example has now also been fixed, after I discovered it will lead to lots of unwanted indentation in code bases that rely on ASI:

```javascript
var a = 1
b = 2
c = 3
```

The previously introduced regex for `;` has even been removed from DjJS mode, so it does not rely on semicolons at all to determine the indentation!

**Comment by JaapJoris** [comment]
Hi there, I'd just like to inform you that [DjHTML 3.0.0](https://github.com/rtts/djhtml/releases/tag/3.0.0) has just been released, including a fix for this bug. Thanks again for reporting it and I'm looking forward to more bugs in the future!
