### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by yeoki-ed** [rtts/djhtml#84]
Hi,

Is there an official VS-code extension for djhtml?

I found this one:
https://marketplace.visualstudio.com/items?itemName=TomUsher.djhtml-vscode

But it's not working properly.

Thanks

**Comment by JaapJoris** [comment]
There are no editor extensions included in DjHTML itself, but I'm hereby paging doctor @tomusher to perhaps give some support in getting his VS Code extension to work properly :pray: 

Otherwise, you can also use the generic [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extension to run the `djhtml` command whenever a file is saved.

**Comment by tomusher** [comment]
I'd love to get this extension working properly but I am swamped! Hoping for some free time in the coming weeks, but in the meantime, contributions welcome.

**Comment by JaapJoris** [comment]
Thanks @tomusher for your quick response! Feel absolutely no pressure to work on this, because as I said the Run on Save extension is a viable alternative. And if there are people reading this who feel like contributing, the djhtml-vscode extension is here: https://github.com/tomusher/djhtml-vscode

**Comment by yeoki-ed** [comment]
Thank you @JaapJoris @tomusher for the response! Appreciate it. 🙏
